<a href="https://colab.research.google.com/github/DouglasP15/Treinamento-Phyton-Generation-/blob/main/Aula%20sobre%20armazenamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# para instalar uma bibliotecaa eu uso o comando :
# no collab !pip install
#fora do collab é apenas pip install
!pip install pandas
!pip install numpy
!pip install matplotlib plotly scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [4]:
# para colocar a bibliotecaa em uso, devemos importar ela
# importe NOME_DA_BIBLIOTECA as APELIDO_PARA_USO
import pandas as pd

In [7]:
#criar o 'esqueleto' do arquivo

# vammos usar dicionarios para criar os dados
# dicionario funciona com a ideia de chave-valor ou chave-valores

dados = {
    'nome':['Katia','Douglas','Matheus','Thiago'],
    'idade':[32,28,23,20],
    'cidade':['Campinas','Campinas','Campinas','Campinas']
}

# a pandas pode transformar um dicionario em uma 'tabela'
# esse pedaço de tabela é chamado de DataFrame

# para transformar
df_dados = pd.DataFrame(dados)

display(df_dados)

      nome  idade    cidade
0    Katia     32  Campinas
1  Douglas     28  Campinas
2  Matheus     23  Campinas
3   Thiago     20  Campinas

In [9]:
#criar um arquivo csv ('excel')

# para criar, precisamos de dados
# chamamos os dados e atribuimos a função to_csv/doc/ect

df_dados.to_csv('teste_dados.csv', index=False)

In [10]:
# como ler um arquivo que me enviaram

df_ler_dados = pd.read_csv('/content/teste_dados.csv')

#comando para ler as primeiras infos do arquivo
df_ler_dados.head()

      nome  idade    cidade
0    Katia     32  Campinas
1  Douglas     28  Campinas
2  Matheus     23  Campinas
3   Thiago     20  Campinas

In [11]:
# vamos popular a tabela

novos_dados = {
    'nome':['Elaine','Ana','Maria'],
    'idade':[49,73,61],
    'cidade':['Sousas','Campinas','Campinas']
}

# sempre que eu quero trabalhar com dados, preciso fazer ser dados
df_novos_dados = pd.DataFrame(novos_dados)

# agora temos que juntar o antigo com o novo
# juntar = concatenar
# cria a base que vai receber todos os dados
# usa a função pd.concat para 'juntar' os dados
# pd.concat([df_ler_dados, df_novos_dados], ignore_index=True
df_dados_juntos = pd.concat([df_ler_dados, df_novos_dados], ignore_index=True)

# voltar para o csv
df_dados_juntos.to_csv('teste_dados.csv', index=False)
display(df_dados_juntos)

      nome  idade    cidade
0    Katia     32  Campinas
1  Douglas     28  Campinas
2  Matheus     23  Campinas
3   Thiago     20  Campinas
4   Elaine     49    Sousas
5      Ana     73  Campinas
6    Maria     61  Campinas