<a href="https://colab.research.google.com/github/DouglasP15/Treinamento-Phyton-Generation-/blob/main/ETL_api_AWS_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vc precisa colocar o drive da empresa no sistema
from google.colab import drive

#para colocar os dados do drive colab
drive.mount('/content/drive_empresa')

Mounted at /content/drive_empresa

In [2]:
# se vem da aws
!pip install boto3 awscli

Collecting boto3
  Downloading boto3-1.43.24-py3-none-any.whl.metadata (6.6 kB)
Collecting awscli
  Downloading awscli-1.45.24-py3-none-any.whl.metadata (11 kB)
Collecting botocore<1.44.0,>=1.43.24 (from boto3)
  Downloading botocore-1.43.24-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.19.0,>=0.18.0 (from boto3)
  Downloading s3transfer-0.18.0-py3-none-any.whl.metadata (1.7 kB)
Collecting docutils<=0.19,>=0.18.1 (from awscli)
  Downloading docutils-0.19-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: PyYAML<6.1,>=3.10 in /usr/local/lib/python3.12/dist-packages (from awscli) (6.0.3)
Collecting colorama<0.4.7,>=0.2.5 (from awscli)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting rsa<4.8,>=3.1.2 (from awscli)
  Downloading rsa-4.7.2-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.24->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.44.0,>=1.43.24->boto3) (2.5.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from rsa<4.8,>=3.1.2->awscli) (0.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.24->boto3) (1.17.0)
Downloading boto3-1.43.24-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.5/140.5 kB 4.9 MB/s eta 0:00:00
Downloading awscli-1.45.24-py3-none-any.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 63.5 MB/s eta 0:00:00
Downloading botocore-1.43.24-py3-none-any.whl (15.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 83.4 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading docutils-0.19-py3-none-any.whl (570 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 27.6 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading rsa-4.7.2-py3-none-any.whl (34 kB)
Downloading s3transfer-0.18.0-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.6/88.6 kB 7.1 MB/s eta 0:00:00
Installing collected packages: rsa, jmespath, docutils, colorama, botocore, s3transfer, boto3, awscli
  Attempting uninstall: rsa
    Found existing installation: rsa 4.9.1
    Uninstalling rsa-4.9.1:
      Successfully uninstalled rsa-4.9.1
  Attempting uninstall: docutils
    Found existing installation: docutils 0.21.2
    Uninstalling docutils-0.21.2:
      Successfully uninstalled docutils-0.21.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sphinx 8.2.3 requires docutils<0.22,>=0.20, but you have docutils 0.19 which is incompatible.
Successfully installed awscli-1.45.24 boto3-1.43.24 botocore-1.43.24 colorama-0.4.6 docutils-0.19 jmespath-1.1.0 rsa-4.7.2 s3transfer-0.18.0

In [4]:
# conectar de api
import requests
import pandas as pd
# para coletar dados da api preciso do endpoint
url = 'https://api.open-meteo.com/v1/forecast?latitude=-23.090000&longitude=-47.218000&current_weather=true'

#vamos descobrir se a api esta funcionando
resposta = requests.get(url)
#status code 200 é ok
if resposta.status_code == 200:
  # é só chamar o que a gente precisa dos dados
  # geralmente dados de api vem no formato json
  dados_json = resposta.json()
  clima_atual = dados_json.get("current_weather")

  # usar pandas para exibir
  df_clima = pd.DataFrame([clima_atual])
  display(df_clima)

,time,interval,temperature,windspeed,winddirection,is_day,weathercode
0,2026-06-08T13:15,900,19.4,2.7,32,1,0

In [8]:
# para usar uma versao não instalada do sql usamos
import sqlite3

#para ler um arquivo .sql
#deve-se criar uma conexão temporaria
conn = sqlite3.connect('memory:')
cursor = conn.cursor()

# o colab, temporariamente é nosso "workbench"
cursor.executescript('''
    create table teste(
    teste_id int primary key,
    nome_teste varchar(255) not null,
    numero_teste integer not null
    );
    ''')

conn.commit()
query_e = '''
select * from teste;
'''

#paraa ver os dados da query, devemos usar o pandas
df_query = pd.read_sql(query_e, conn)

display(df_query)

Empty DataFrame
Columns: [teste_id, nome_teste, numero_teste]
Index: []